
INSERT IGNORE INTO services (name, description) VALUES
('Vidange + Filtre à Huile',
 'Remplacement de l’huile moteur et du filtre à huile ; contrôle des niveaux et remise à zéro de l’indicateur.'),
('Kit de Courroie de Distribution (changement)',
 'Remplacement du kit de distribution : courroie, galets tendeurs et pompe à eau si applicable.'),
('Disques et Plaquettes Avant (changement)',
 'Remplacement des disques et plaquettes de frein avant ; nettoyage/rodage et purge si nécessaire.'),
('Kit d’Embrayage (changement)',
 'Remplacement du mécanisme, du disque et de la butée d’embrayage ; contrôle émetteur/récepteur.'),
('Plaquettes Avant (changement)',
 'Remplacement des plaquettes de frein avant ; contrôle de l’usure et de l’épaisseur des disques.'),
('Amortisseurs Avant (changement)',
 'Remplacement des amortisseurs avant (avec coupelles si nécessaire) ; contrôle de la géométrie.'),
('Kit d’Embrayage et Volant Moteur (changement)',
 'Remplacement du kit d’embrayage et du volant moteur (bi-masse le cas échéant).'),
('Filtre d’Habitacle (changement)',
 'Remplacement du filtre d’habitacle (pollen/charbon actif) pour améliorer la qualité d’air et le désembuage.'),
('Disques et Plaquettes Arrière (changement)',
 'Remplacement des disques et plaquettes arrière ; réglage/contrôle du frein de stationnement.');


INSERT INTO services_garages (services_id, garages_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 5),
       (6, 1),
       (6, 2),
       (6, 3),
       (7, 1),
       (7, 2);


      INSERT INTO garage_services ( garage_id,services_id)
       VALUES (1, 1),
              (1, 2),
              (1, 3),
              (1, 4),
              (1, 5),
              (2, 1),
              (2, 2),
              (2, 3),
              (2, 4),
              (2, 5),
              (3, 1),
              (3, 2),
              (3, 3),
              (3, 4),
              (3, 5),
              (4, 1),
              (4, 2),
              (4, 3),
              (4, 4),
              (4, 5),
              (5, 1),
              (5, 2),
              (5, 3),
              (5, 4),
              (5, 5),
              (6, 1),
              (6, 2),
              (6, 3),
              (7, 1),
              (7, 2);

