INSERT INTO services (name, description)
VALUES ('Vidange moteur',
        'Remplacement de l’huile moteur et du filtre à huile pour assurer le bon fonctionnement du moteur.'),
       ('Changement de pneus', 'Montage, équilibrage et remplacement des pneus usés.'),
       ('Freinage', 'Contrôle et remplacement des plaquettes et disques de frein.'),
       ('Contrôle technique',
        'Vérification complète du véhicule pour répondre aux normes de sécurité et environnementales.'),
       ('Climatisation', 'Recharge et entretien du système de climatisation du véhicule.');

INSERT INTO services_garages (services_id, garages_id)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (2, 1),
       (2, 2),
       (2, 3),
       (2, 4),
       (2, 5),
       (3, 1),
       (3, 2),
       (3, 3),
       (3, 4),
       (3, 5),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 4),
       (4, 5),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 4),
       (5, 5),
       (6, 1),
       (6, 2),
       (6, 3),
       (7, 1),
       (7, 2);



       INSERT INTO garage_services ( garage_id,services_id)
       VALUES (1, 1),
              (1, 2),
              (1, 3),
              (1, 4),
              (1, 5),
              (2, 1),
              (2, 2),
              (2, 3),
              (2, 4),
              (2, 5),
              (3, 1),
              (3, 2),
              (3, 3),
              (3, 4),
              (3, 5),
              (4, 1),
              (4, 2),
              (4, 3),
              (4, 4),
              (4, 5),
              (5, 1),
              (5, 2),
              (5, 3),
              (5, 4),
              (5, 5),
              (6, 1),
              (6, 2),
              (6, 3),
              (7, 1),
              (7, 2);
